# Generated by Django 5.0.6 on 2024-05-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog1', models.CharField(max_length=30)),
                ('blog2', models.CharField(max_length=30)),
                ('blog3', models.CharField(max_length=30)),
            ],
        ),
    ]
